---
title: "Datenset"
output: html_document
date: "2025-04-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
MS_Table = read.table("RDeeP_HeLa_Interphase.csv", header=TRUE, row.names=1, sep = ";")
```

```{r}
Fraktionsnamen = c('Fraction1_Ctrl', 'Fraction1_RNAse', 'Fraction2_Ctrl', 'Fraction2_RNAse','Fraction3_Ctrl', 'Fraction3_RNAse','Fraction4_Ctrl', 'Fraction4_RNAse','Fraction5_Ctrl', 'Fraction5_RNAse','Fraction6_Ctrl', 'Fraction6_RNAse','Fraction7_Ctrl', 'Fraction7_RNAse','Fraction8_Ctrl', 'Fraction8_RNAse','Fraction9_Ctrl', 'Fraction9_RNAse','Fraction10_Ctrl', 'Fraction10_RNAse','Fraction11_Ctrl', 'Fraction11_RNAse','Fraction12_Ctrl', 'Fraction12_RNAse','Fraction13_Ctrl', 'Fraction13_RNAse','Fraction14_Ctrl', 'Fraction14_RNAse','Fraction15_Ctrl', 'Fraction15_RNAse','Fraction16_Ctrl', 'Fraction16_RNAse','Fraction17_Ctrl', 'Fraction17_RNAse','Fraction18_Ctrl', 'Fraction18_RNAse','Fraction19_Ctrl', 'Fraction19_RNAse','Fraction20_Ctrl', 'Fraction20_RNAse','Fraction21_Ctrl', 'Fraction21_RNAse','Fraction22_Ctrl', 'Fraction22_RNAse','Fraction23_Ctrl', 'Fraction23_RNAse','Fraction24_Ctrl', 'Fraction24_RNAse','Fraction25_Ctrl', 'Fraction25_RNAse')
```

```{r}
meantabellen = c('mean_Fraction1_Ctrl', 'mean_Fraction1_RNAse', 'mean_Fraction2_Ctrl', 'mean_Fraction2_RNAse','mean_Fraction3_Ctrl', 'mean_Fraction3_RNAse','mean_Fraction4_Ctrl', 'mean_Fraction4_RNAse','mean_Fraction5_Ctrl', 'mean_Fraction5_RNAse','mean_Fraction6_Ctrl', 'mean_Fraction6_RNAse','mean_Fraction7_Ctrl', 'mean_Fraction7_RNAse','mean_Fraction8_Ctrl', 'mean_Fraction8_RNAse','mean_Fraction9_Ctrl', 'mean_Fraction9_RNAse','mean_Fraction10_Ctrl', 'mean_Fraction10_RNAse','mean_Fraction11_Ctrl', 'mean_Fraction11_RNAse','mean_Fraction12_Ctrl', 'mean_Fraction12_RNAse','mean_Fraction13_Ctrl', 'mean_Fraction13_RNAse','mean_Fraction14_Ctrl', 'mean_Fraction14_RNAse','mean_Fraction15_Ctrl', 'mean_Fraction15_RNAse','mean_Fraction16_Ctrl', 'mean_Fraction16_RNAse','mean_Fraction17_Ctrl', 'mean_Fraction17_RNAse','mean_Fraction18_Ctrl', 'mean_Fraction18_RNAse','mean_Fraction19_Ctrl', 'mean_Fraction19_RNAse','mean_Fraction20_Ctrl', 'mean_Fraction20_RNAse','mean_Fraction21_Ctrl', 'mean_Fraction21_RNAse','mean_Fraction22_Ctrl', 'mean_Fraction22_RNAse','mean_Fraction23_Ctrl', 'mean_Fraction23_RNAse','mean_Fraction24_Ctrl', 'mean_Fraction24_RNAse','mean_Fraction25_Ctrl', 'mean_Fraction25_RNAse')
```

```{r}
Replikatsnamen = c('Ctrl1_norm_mittel','Ctrl2_norm_mittel','Ctrl3_norm_mittel','RNAse1_norm_mittel','RNAse2_norm_mittel','RNAse3_norm_mittel')
```

```{r}
SW_Replikatsnamen = c('SW_Ctrl1','SW_Ctrl2','SW_Ctrl3','SW_RNAse1','SW_RNAse2','SW_RNAse3')
```

```{r}
SW_Replikatsnamen_norm = c('SW_Ctrl1_norm','SW_Ctrl2_norm','SW_Ctrl3_norm','SW_RNAse1_norm','SW_RNAse2_norm','SW_RNAse3_norm')
```

```{r}
Treatmentnamen = c('Ctrl1_norm','Ctrl2_norm','Ctrl3_norm','RNAse1_norm','RNAse2_norm','RNAse3_norm')

```

# Beschreibung der Daten

### Dimensionen der Tabelle:

```{r}
dim(MS_Table)
```

### Spaltennamen

```{r}
colnames(MS_Table)
```

### Reihennamen

```{r}
rownames(MS_Table)
```

### Anzahl an fehlenden Werte

```{r}
sum(is.na(MS_Table))
```

### Überprüfen ob die Werte alle 'numeric' sind

```{r}
sum(sapply(MS_Table, is.numeric))
# da kommt 150 raus > heißt alle spalten sind numerisch
```

# Normierung

```{r}
# Erstellen von subtabellen
for (i in 1:50) {
  spalten_index = ((i-1) * 3 + 1):(i * 3) # pro loop 3 Spalten zusammen
  teilmatrix = MS_Table[,spalten_index]
  
  assign(Fraktionsnamen[i], teilmatrix) # wählt gleich den passenden Namen dazu aus
}
```

```{r}
# Mittelwerte von den Spalten jeweils als Vektor
for (i in 1:50) {
  spalten_index = ((i-1) * 3 + 1):(i * 3) # pro loop 3 Spalten zusammen
  teilmatrix = MS_Table[,spalten_index]
  
  Mittelwerte = colMeans(teilmatrix)
  
  assign(paste0('mean_', Fraktionsnamen[i]), Mittelwerte) # wählt gleich den passenden Namen dazu aus
}
```

```{r}
# Normierungsfaktor pro Fraktion
normf.fraktion = c()
for (i in 1:50) {
    
  # Differenzen von jeweils einzelnen Mittelwerten bilden
  abstand_12 = abs(get(meantabellen[i])[1] - get(meantabellen[i])[2] )
  abstand_13 = abs(get(meantabellen[i])[1] - get(meantabellen[i])[3] )
  abstand_23 = abs(get(meantabellen[i])[2] - get(meantabellen[i])[3] )
  
  # kleinste Differenz bestimmen + Mittelwert aus den kleinsten Differenzen berechnen
  if (abstand_12 <= abstand_13 && abstand_12 <= abstand_23) {
    normf.fraktion[i] = (mean(c(get(meantabellen[i])[1], get(meantabellen[i])[2])))
  } else if (abstand_13 <= abstand_12 && abstand_13 <= abstand_23) {
    normf.fraktion[i] = (mean(c(get(meantabellen[i])[1], get(meantabellen[i])[3])))
  } else{
    normf.fraktion[i] = (mean(c(get(meantabellen[i])[2], get(meantabellen[i])[3])))
  }
}
 normf.fraktion
```

```{r}
# Normierungsfaktor für jedes Replikat 
# normierungsfaktor pro Fraktion durch Mittelwert des Replikats teilen
normf.rep = c()
for (i in 1:50) { # 
  for (j in 1:3) {
  normf.rep = c(normf.rep, normf.fraktion[i] / get(meantabellen[i])[j])
  }
}
normf.rep
```

```{r}
# Normierung der Daten auf Mittelwert 
# anwenden der Normierungsfaktoren der Replikate auf das zugehörige Replikat
MS_Table_norm_mittel = as.data.frame(matrix(NA, nrow = nrow(MS_Table), ncol = 150))
for (i in 1:150) {
  MS_Table_norm_mittel[,i] = normf.rep[i] * MS_Table[,i]
}
colnames(MS_Table_norm_mittel) = colnames(MS_Table)
rownames(MS_Table_norm_mittel) = rownames(MS_Table)

MS_Table_norm_mittel
```

```{r}
# Normierung der Daten auf 100 mit Sliding window
# Subtabellen für einzelne Replikate

for (i in 1:6) {

  spalten_index = seq(from = i, to = 150, by = 6)
  teilmatrix = MS_Table_norm_mittel[, spalten_index]
  
  assign(Replikatsnamen[i], teilmatrix)
}
```

```{r}
# Sliding window
for (i in 1:6) {
  
  teilmatrix = data.frame(get(Replikatsnamen[i])[1], (get(Replikatsnamen[i])[1:23] + get(Replikatsnamen[i])[2:24] + get(Replikatsnamen[i])[3:25]) / 3, get(Replikatsnamen[i])[25]) # 
  
  
  assign(SW_Replikatsnamen[i], teilmatrix) # wählt gleich den passenden Namen dazu aus
}
```


```{r}
for (i in 1:6) {
  
  teilmatrix = (get(SW_Replikatsnamen[i])) * 100 / rowSums(get(SW_Replikatsnamen[i]))
  
  assign(SW_Replikatsnamen_norm[i], teilmatrix) # wählt gleich den passenden Namen dazu aus
}
```

```{r}
# Zusammenführen zu einer Tabelle

matrizen <- list(SW_Ctrl1_norm,SW_Ctrl2_norm,SW_Ctrl3_norm,SW_RNAse1_norm,SW_RNAse2_norm,SW_RNAse3_norm)

MS_Table_norm = c()

for (i in 1:25) {
  for (j in 1:6) {
    MS_Table_norm = as.data.frame(cbind(MS_Table_norm, matrizen[[j]][, i]))
  }
}

colnames(MS_Table_norm) = colnames(MS_Table)
rownames(MS_Table_norm) = rownames(MS_Table)

MS_Table_norm
```

# Reproduzierbarkeit

Erklärung welche Korrelation wird uns abgeschaut haben:

Pearson oder Spearmean =\> ohne Ränge weil wir ganz viele Nullen haben !! heißt [Pearson]{.underline}

Vorgehen:

```{r}
# Vektor für Korrelationen zwischen Spalten 1 & 2
kor_Spalte1_Spalte2 = c()
for (i in 1:50) {
  spalten_index = ((i-1) * 3 + 1):(i * 3) # pro loop 3 Spalten zusammen
  teilmatrix = MS_Table_norm[,spalten_index] # die Untertabellen für jede einzelne Fraktion
  
  kor_a = cor(teilmatrix[,1], teilmatrix[,2], method = 'pearson', use = "complete.obs") # Pearsonkorrelation von Spalte 1 & 2
  kor_Spalte1_Spalte2 = c(kor_Spalte1_Spalte2,kor_a) # an Vektor anhängen
}

kor_Spalte1_Spalte2
```

```{r}
# Vektor für Korrelationen zwischen Spalten 2 & 3
kor_Spalte2_Spalte3 = c()
for (i in 1:50) {
  spalten_index = ((i-1) * 3 + 1):(i * 3) # pro loop 3 Spalten zusammen
  teilmatrix = MS_Table_norm[,spalten_index] # die Untertabellen für jede einzelne Fraktion
  
  kor_b = cor(teilmatrix[,2], teilmatrix[,3], method = 'pearson', use = "complete.obs") # Pearsonkorrelation von Spalte 2 & 3
  kor_Spalte2_Spalte3 = c(kor_Spalte2_Spalte3,kor_b) # an Vektor anhängen
}

kor_Spalte2_Spalte3
```

```{r}
# Vektor für Korrelationen zwischen Spalten 1 & 3
kor_Spalte1_Spalte3 = c()
for (i in 1:50) {
  spalten_index = ((i-1) * 3 + 1):(i * 3) # pro loop 3 Spalten zusammen
  teilmatrix = MS_Table_norm[,spalten_index] # die Untertabellen für jede einzelne Fraktion
  
  kor_c = cor(teilmatrix[,2], teilmatrix[,3], method = 'pearson', use = "complete.obs") # Pearsonkorrelation von Spalte 1 & 3
  kor_Spalte1_Spalte3 = c(kor_Spalte1_Spalte3,kor_c) # an Vektor anhängen
}

kor_Spalte1_Spalte3
```

```{r}
kor_tabelle = cbind(kor_Spalte1_Spalte2, kor_Spalte2_Spalte3, kor_Spalte1_Spalte3)
rownames(kor_tabelle) = Fraktionsnamen
kor_tabelle
```

```{r}
# scatterPlot beispielhaft als Deliverable Reprodzierbarkeit
Crtl.1.1 = MS_Table_norm[,1]
Crtl.1.2 = MS_Table_norm[,2]

plot(Crtl.1.1, Crtl.1.2, 
     pch = 20,
     xlab = 'Crtl.1.1',
     ylab = 'Crtl.1.2',)
```

```{r}
# pairs(MS_Table_norm[1:9], pch=20, cex=0.5)
# vielleicht so ähnlich, aber übersichtlicher, soll das aufs Plakat?
```
```{r}
max(MS_Table_norm[1,])
```
# Data exploration
```{r}
for (i in 1:6) {

  spalten_index = seq(from = i, to = 150, by = 6) 
  teilmatrix = MS_Table_norm[, spalten_index]
  
  assign(Treatmentnamen[i], teilmatrix) # neue Subtabellen, richtig benannt
}
```


```{r}
for (i in 1:6) {
  Tabelle = get(Treatmentnamen[i])
  
  # Maximalwert pro Zeile (y)
  abs.Max = c(apply(Tabelle, 1, max))
  
  # Spaltenindex (x als Position)
 Fraktion = c(apply(Tabelle, 1, which.max))
  
  # Erstelle einen Dataframe mit x und y
  teildata = cbind(
    Fraktion, abs.Max
  )
  
  # Speichere den Dataframe z.B. als maxima_df1, maxima_df2, ...
  assign(paste0('abs.Max_', Treatmentnamen[i]), teildata)
}

```




